### ISSUE TITLE
Write "Installation Setup" handbook section.

### ISSUE THREAD

**Issue by seekanddefine** [athensresearch/handbook#19]
> https://athensresearch.gitbook.io/handbook/community/athens-guide/getting-started/installation-guide

> https://github.com/athensresearch/handbook/blob/main/community/athens-guide/getting-started/installation-guide.md

**Comment by elazar** [comment]
:wave: I'd like to start working on this issue.

**Comment by joelhans** [comment]
@elazar Assigned to you and moved to in-progress!

**Comment by joelhans** [comment]
First off, I updated the top comment with new links to the published doc and the `.md` file. That should help a bit. Otherwise (and maybe sadly) the fixes I envision here are a bit... transactional? Not a ton of creativity at play here.

Otherwise, some TODOs:

- Change **Hosting Your Own Data** section to something like **Syncing your data between machines**.
- Add a section about the self-hosted backend.
  - The athensresearch/backend repo is archived, but can still be used for now.
  - In the future, all the self-hosted code will exist in the athens/athens repo.
- Move "If you're coming to Athens from Roam Research, check out the import doc for details on how to bring your Roam content over to Athens." to the **Import a Preexisting Database** section.
- Maybe add some information about _where_ Athens puts the database files?
- Optionally, a short description of what the `index.transit` file is.
